DELETE http://localhost:3003/api/blogs/66de214dbd49a24d7f10ee29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ5cm9uIiwiaWQiOiI2NmRlMWMyNDhlY2RmODM5NDMzYTE4MmUiLCJpYXQiOjE3MjU4OTU4NjF9.YhTfSTEe6HU1HDG-DW-qWAwm9cZ98E8ZUrqxdTDGQ1g