POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvY2t5IiwiaWQiOiI2NmRjMmYyZTFjN2E2NTNiZjk3MTdlYjkiLCJpYXQiOjE3MjU4MjE4Mzd9.C29yBrbFvvfdDhtZvrIpmJ2HDVZQYtH9aMTQOXyhw-E

{
  "content": "Single page apps use token bases auth",
  "important": false
}