DELETE http://localhost:3003/api/blogs/66e6b9f33afb962dbb4f8816
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvY2t5IiwiaWQiOiI2NmRlMWMxNThlY2RmODM5NDMzYTE4MmMiLCJpYXQiOjE3MjYzOTY5ODF9.bNT-vzUFLXGNYW3GI2J9enzNBSjUlyKj2n3v5e4eaaU